@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun May 18 01:33:21 +0800 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim MLDSA_AXI_Top_tb_behav -key {Behavioral:sim_1:Functional:MLDSA_AXI_Top_tb} -tclbatch MLDSA_AXI_Top_tb.tcl -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage1.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/MLDSA_AXI_Top_tb_behav.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage2.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage3.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage4.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage5.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage6.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage7.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage8.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage9.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage10.wcfg -log simulate.log"
call xsim  MLDSA_AXI_Top_tb_behav -key {Behavioral:sim_1:Functional:MLDSA_AXI_Top_tb} -tclbatch MLDSA_AXI_Top_tb.tcl -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage1.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/MLDSA_AXI_Top_tb_behav.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage2.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage3.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage4.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage5.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage6.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage7.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage8.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage9.wcfg -view C:/Users/USER/Desktop/ML_DSA_syn_new/IMP4/MLDSA/SignVer_Stage10.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
