# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP2/Data_Mem/Data_Mem.srcs/sources_1/ip/Ture_Dual_Port_RAM_23x1024/Ture_Dual_Port_RAM_23x1024.xci
# IP: The module: 'Ture_Dual_Port_RAM_23x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP2/Data_Mem/Data_Mem.gen/sources_1/ip/Ture_Dual_Port_RAM_23x1024/Ture_Dual_Port_RAM_23x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ture_Dual_Port_RAM_23x1024'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP2/Data_Mem/Data_Mem.srcs/sources_1/ip/Ture_Dual_Port_RAM_23x1024/Ture_Dual_Port_RAM_23x1024.xci
# IP: The module: 'Ture_Dual_Port_RAM_23x1024' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP2/Data_Mem/Data_Mem.gen/sources_1/ip/Ture_Dual_Port_RAM_23x1024/Ture_Dual_Port_RAM_23x1024_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ture_Dual_Port_RAM_23x1024'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
