# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP3/MLDSA/MLDSA.srcs/sources_1/ip/Ture_Dual_Port_RAM_23x4096/Ture_Dual_Port_RAM_23x4096.xci
# IP: The module: 'Ture_Dual_Port_RAM_23x4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP3/MLDSA/MLDSA.gen/sources_1/ip/Ture_Dual_Port_RAM_23x4096_3/Ture_Dual_Port_RAM_23x4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ture_Dual_Port_RAM_23x4096'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP3/MLDSA/MLDSA.srcs/sources_1/ip/Ture_Dual_Port_RAM_23x4096/Ture_Dual_Port_RAM_23x4096.xci
# IP: The module: 'Ture_Dual_Port_RAM_23x4096' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP3/MLDSA/MLDSA.gen/sources_1/ip/Ture_Dual_Port_RAM_23x4096_3/Ture_Dual_Port_RAM_23x4096_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ture_Dual_Port_RAM_23x4096'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
