@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 26 04:14:41 +0800 2025
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Modular_Reduction_tb_time_synth -key {Post-Synthesis:sim_1:Timing:Modular_Reduction_tb} -tclbatch Modular_Reduction_tb.tcl -view C:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP2/Modular_Reduction/Modular_Reduction_tb_behav.wcfg -log simulate.log"
call xsim  Modular_Reduction_tb_time_synth -key {Post-Synthesis:sim_1:Timing:Modular_Reduction_tb} -tclbatch Modular_Reduction_tb.tcl -view C:/Users/fossu/Desktop/ML_DSA_Syn_new/IMP2/Modular_Reduction/Modular_Reduction_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
